<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet href="styles.xsl" type="text/xsl" ?>
<!--
	File name:		budget.xml
	Developer:		Bradley Turner
	Date Created:	24/08/16
	
	Last modified:	19/10/16
-->

<!--Inline DTD-->
<!DOCTYPE rooms
[
	<!ELEMENT rooms (room+)>
	<!ATTLIST rooms type (luxury | budget) #REQUIRED>
	<!ATTLIST rooms available (CDATA) #REQUIRED>
	
		<!ELEMENT room (name, people+, cost, location, photo_file+, guest_reviews_link, description?, wifi?, fourPostBed?, gardenAccess, vineyardTour)*>
			<!-- MANDATORY-->
			<!ELEMENT name (#PCDATA)>	
			
			<!ELEMENT people EMPTY> 
			<!ATTLIST people capacity CDATA #REQUIRED>
			
			<!ELEMENT cost EMPTY>
			<!ATTLIST cost perNight (100|250) #REQUIRED>
			
			<!ELEMENT location EMPTY> 
			<!ATTLIST location story (ground | floor1 | floor2) #REQUIRED>
			
			<!ELEMENT photo_file (#PCDATA)>
			
			<!ELEMENT guest_reviews_link (#PCDATA)> 
			
			<!-- ADDITIONAL EXTRAS>-->
			<!ELEMENT description (#PCDATA)> 
			
			<!ELEMENT wifi EMPTY>
			<!ATTLIST wifi inc (yes|no) #IMPLIED>
			
			<!ELEMENT fourPostBed EMPTY>
			<!ATTLIST fourPostBed inc (yes|no) #IMPLIED>
			
			<!ELEMENT gardenAccess EMPTY>
			<!ATTLIST gardenAccess inc (yes|no) #REQUIRED>
			
			<!ELEMENT vineyardTour (#PCDATA)>
			<!ATTLIST vineyardTour inc (yes|no) #REQUIRED>
			<!ATTLIST vineyardTour extraCharge (0|50|100) #REQUIRED>

	
	
	<!-- MANDATORY ENTITY-->		
	<!ENTITY AC "air conditioning">
	<!ENTITY PB "private bathroom">
	
]>



<!--XML TEMPLATE-->
<rooms type="budget" available="3">
	
	<room>
		<name>Pale-headed Rosella</name>
		<people capacity="2" />
		<cost perNight="100" />
		<location story="floor1" />
		<photo_file>images/budgetRoom3.jpg</photo_file>
		<guest_reviews_link>https://www.tripadvisor.com.au/</guest_reviews_link>
		<description>
			With its high vaulted ceilings and tasteful furnishings, you will find yourself drawn to this room.
			Couples can expect breakfast in bed with amazing views looking over the surrounding hillsides,
			and for an affordable price of $100/night.
		</description>
		<wifi inc="yes" />
		<fourPostBed inc="no" />				
		<gardenAccess inc="no" />
		<vineyardTour inc="yes" extraCharge="50">
			Adelaide Hills - Half-day wine tasting tour
		</vineyardTour>
	</room>

	<room>
		<name>Green Rosella</name>
		<people capacity="4" />
		<cost perNight="100" />
		<location story="floor1" />
		<photo_file>images/budgetRoom2.jpg</photo_file>
		<guest_reviews_link>https://www.tripadvisor.com.au/</guest_reviews_link>
		<description>
			Located on the first floor, you will be swept away with the views. With breakfast, &AC;, 
			and wifi included, you'll find it hard to get out of bed.
		</description>
		<wifi inc="yes" />
		<fourPostBed inc="no" />				
		<gardenAccess inc="no" />
		<vineyardTour inc="no" extraCharge="0" />
	</room>

	<room>
		<name>Crimson Rosella</name>
		<people capacity="2" />
		<cost perNight="100" />
		<location story="ground" />
		<photo_file>images/budgetRoom1.jpg</photo_file>
		<guest_reviews_link>https://www.tripadvisor.com.au/</guest_reviews_link>
		<description>
			This room can be summed up with one simple statement, "warm and cozy". This ground floor suite
			will entice people from all walks of life with its large four poster bed and soft drapes. With
			&AC; and wifi provided it will provide for any occasion. However if you do want to explore the
			local area, there is a half-day wine tasting tour included.
		</description>
		<wifi inc="yes" />
		<fourPostBed inc="no" />				
		<gardenAccess inc="yes" />
		<vineyardTour inc="no" extraCharge="0" />
			
	</room>
</rooms>