<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet href="roomStyling.xsl" type="text/xsl" ?>
<!--

	File name:		template.xml
	Developer:		Bradley Turner
	Date Created:	24/08/16
	
	Last modified:	09/09/16
-->

<!--Inline DTD-->
<!DOCTYPE rooms[
	<!ELEMENT rooms (room+)>
	<!ATTLIST rooms type (luxury | budget) #REQUIRED>
	<!ATTLIST rooms available (CDATA) #REQUIRED>
	
		<!ELEMENT room (name, people+, cost_pn, location, photo_file+, guest_reviews_link, description?, wifi?, fourPostBed?, gardenAccess, vineyardTour)*>
			<!-- MANDATORY-->
			<!ELEMENT name (#PCDATA)>	
			
			<!ELEMENT people EMPTY> 
			<!ATTLIST people capacity CDATA #REQUIRED>
			
			<!ELEMENT cost EMPTY>
			<!ATTLIST cost perNight (100|250) #REQUIRED>
			
			<!ELEMENT location EMPTY> 
			<!ATTLIST location story (ground | floor1 | floor2) #REQUIRED>
			
			<!ELEMENT photo_file (#PCDATA)>
			
			<!ELEMENT guest_reviews_link (#PCDATA)> 
			
			<!-- ADDITIONAL EXTRAS>-->
			<!ELEMENT description (#PCDATA)> 
			
			<!ELEMENT wifi EMPTY>
			<!ATTLIST wifi inc (yes|no) #IMPLIED>
			
			<!ELEMENT fourPostBed EMPTY>
			<!ATTLIST fourPostBed inc (yes|no) #IMPLIED>
			
			<!ELEMENT gardenAccess EMPTY>
			<!ATTLIST gardenAccess inc (yes|no) #REQUIRED>
			
			<!ELEMENT vineyardTour (#PCDATA)>
			<!ATTLIST vineyardTour inc (yes|no) #REQUIRED>
			<!ATTLIST vineyardTour extraCharge (0|50|100) #REQUIRED>

	
	
	<!-- MANDATORY ENTITY-->		
	<!ENTITY AC "Air Conditioned">
	<!ENTITY PB "private bathroom">
]>



<!--XML TEMPLATE-->
<rooms type="luxury" available="3">
	<room>
	
	
		<name>					</name>
		
		<people capacity="2" />
		<cost perNight="250" />
		<location story="ground" />
		
		<photo_file>			</photo_file>
		<guest_reviews_link> 		</guest_reviews_link>
		<!-- ADDITIONAL EXTRAS>-->
		<description>
			Some text about the room perhaps it is &AC;
		</description>
		<wifi inc="yes" />
		<fourPostBed inc="no" />				
		<gardenAccess inc="no" />
		<vineyardTour inc="no" extraCharge="0">		</vineyardTour>
	</room>
	
</rooms>